# This is a basic workflow to help you get started with Actions

name: Single Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ production ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkout: 
    uses: vinayb21/github-action-push-to-another-repo@1.4.0
    with:
      # Source directory from the origin directory
      source-directory: TestAutoCommit
      # Name of the destination username/organization
      destination-github-username: PortoSpots 
      # Destination repository
      destination-repository-name: WebPage
      # Email for the git commit
      user-email: portospots@gmail.com
      # [Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
      commit-message: Automated publish V0.1
